language: java

env:
  global:
    secure: O49V5UfUW/HNHMckPB6kCtkBPJPJ9VeuQ+6DHy4RR89dI44+zebkiHkcU18+JRNv4rbt9UiBHjinPW/RSvtbvvLRn773fH/lGIQPuXpMCHJH/kJZFKB0RO7Orh/yGnG8KThaRbC4Ntbzdettl318o4bbcOrpeoq2u8zpN6CDaOM=

branches:
  only:
  - master

script: mvn clean deploy

notifications:
  email: false
